### ISSUE TITLE
secret 这个该翻译成什么比较好？

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/translation-spec#1]
翻译时，遇到几次 secret ，一直纠结这个改翻译成什么
秘密 or 机密？
总感觉有点别扭

**Comment by LinuxSuRen** [comment]
我倾向于使用“凭据”。但有个小困惑，`secret` 和 `credential` 都是凭据的意思。不过，从意思上感觉没问题。

**Comment by donhui** [comment]
[GitLab 11.9 发布，新增秘密自动检测](https://www.infoq.cn/article/Hg4V4qzOZ8meA4_HuUFs)
这里 secret 翻译成了秘密

**Comment by LinuxSuRen** [comment]
secret 是有秘密的意思，但是，这里感觉不是很合适。个人感觉“凭据”或者不翻译比较好点。

**Comment by donhui** [comment]
嗯 我感觉还是不翻译好点 翻译的话变了味道
